# Generated by Django 3.0.4 on 2020-06-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_email_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_confirmed',
            new_name='email_verified',
        ),
    ]
