# Generated by Django 2.2.14 on 2020-07-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_login_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_secret',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login_method',
        ),
        migrations.RemoveField(
            model_name='user',
            name='superhost',
        ),
    ]
